name: Continuous Integration
on:
  push:
    branches:
    - FinishBot
    paths:
    - 'actions/**'
    - '.github/workflows/action_server.yml'

jobs:
  build_and_deploy:
    name: Build Action Server Docker Image
    runs-on: ubuntu-latest
    #env:
      #DOCKERHUB_USERNAME: oakela
    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@v2
      - id: action_server
        name: Build Actions Server Image
        uses: RasaHQ/rasa-action-server-gha@v1.0.3
        with:
          #actions_directory: 'actions'
          docker_registry_login: ${{ secrets.DOCKER_HUB_LOGIN }}
          docker_registry_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker_image_name: 'jesbec/new_action_server'
          docker_image_tag: ${{ github.sha }}
          #rasa_sdk_version: '2.8.0'
